### ISSUE TITLE
How is the jsCraftCamp spelling?

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#1]
I think we need to agree on two things
1) for the "official" naming (which might use spaces) such as "JS CraftCamp" and
2) the spaceless name for twitter accounts, etc. like "jsCraftCamp"

Let's vote, here are the options, I see
for 1) 
- [ ] 1a) JS CraftCamp
- [ ] 1b) jsCraftCamp
- [ ] 1c) jscraftcamp
- [ ] 1d) JS craftcamp

for 2) 
- [ ] 2a) jscraftcamp  
- [ ] 2b) JScraftcamp  
- [ ] 2c) JsCraftCamp  
- [ ] 2d) JSCraftCamp  

feel free to add more options and let's vote at some point ... or shall we do the voting on twitter with the community?

**Comment by marcoemrich** [comment]
either 1c & 2a simple, only one version needed

or 1a  & 2c (more readable, but looks a bit strange)

I think I prefer 1c & 2a

**Comment by cko** [comment]
1a and 2a

**Comment by wolframkriesing** [comment]
1a+2a
