### ISSUE TITLE
Security for Corona and entrance check 💰💰💰💰💰

### ISSUE THREAD

**Issue by marcoemrich** [jscraftcamp/website#1093]
# Why security and entrance check?
We want to make sure all attendees are as safe as possible at our event. Therefore, we decided to let everybody test negative for COVID-19 shortly before the event. To ensure the safety of us all, we want to have a security / entrance check for these test results.

# How does it work?
We have an offer from a security firm for under 500 € (+ taxes) for both days.

Let's try to be a non-spreading event and allow potentially vulnerable people into the sessions as well. There is a test center nearby to get official tests and if we make it mandatory to have a negative test result <24h, we should be as safe as possible.

**Comment by MsAennaBanaena** [comment]
Hello dear people,

we (Method Park) would love to do this sponsorship package!

Invoice with pleasure simply to:
Method Park Holding AG
Anna Zeidler
Wetterkreuz 19a
91058 Erlangen

Do you need anything else regarding this? 
Kind regards
Anna

**Comment by wolframkriesing** [comment]
hey @MsAennaBanaena this is awesome news. Thank you very much, we will add you to the sponsors on our page.
We will connect you with the security service, that we have booked so they bill you at the address you listed above

**Comment by MsAennaBanaena** [comment]
You've got mail! ♥

**Comment by lowsky** [comment]
thanks!
sponsor logo is live.
