### ISSUE TITLE
Add sponsor page (see 2019)

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#1096]
- show the "what does a sponsor get" page
  - use the items as we had in 2019
  - add 2 more: sponsor can add a "Aufsteller" and add job ads
- move the link from the navigation to this page

**Comment by lowsky** [comment]
Yea, I think this is actually what we had back then:

https://web.archive.org/web/20190725181326/http://jscraftcamp.org/sponsoring.html
