### ISSUE TITLE
Rename from "master" to "main"

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#1125]

**Comment by lowsky** [comment]
Renaming was done via GH on this page:
https://github.com/jscraftcamp/website/settings/branches
-> just by renaming the default branch.

Steps for renaming it on your local development environment:
```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

Replaced the default branch for `Netlify` deployments:
https://app.netlify.com/sites/jscraftcamp/settings/deploys
-> in the `branches` section
