### ISSUE TITLE
Create poll for this years JSCC branding color

### ISSUE THREAD

**Issue by Narigo** [jscraftcamp/website#1287]
We need a fresh color for this year.

**Comment by wolframkriesing** [comment]
throw some colors over the fence!
see some old once: https://github.com/jscraftcamp/logo/blob/master/src/static-logo.js#L1-L5
and the poll https://twitter.com/JSCraftCamp/status/990249027215286274

**Comment by Narigo** [comment]
I asked @michaelzoidl for help with this 😅

**Comment by meldron** [comment]
https://jscraftcamp.github.io/logo/2023/poll.html

**Comment by wolframkriesing** [comment]
we polled in the orga call, and we LOVE green, option 3
