### ISSUE TITLE
Sponsor needed for snacks on Saturday 🍌🍎🍪🍐🍩🍦 - 💰

### ISSUE THREAD

**Issue by meldron** [jscraftcamp/website#1293]
# Why Snacks?
The night before was a party. If the attendees don't need a snack now, they must have some other secret sauce to get their bodies back up to speed. But many rely on a sponsor to help out and prevent a low blood sugar by providing quick energy refilling snacks in the form of sweets, baked goods and candy. Keep those hard working brains happy - either by choosing yourself what to get or just leave it up to us to find the right sugar-bombs!

# How does it work?
Cost ~100,- depending on what the sponsor orders.
Ideally the sponsor orders the snacks, to be delivered to the location. Feel free to ask us in this ticket about details.

In previous years we asked some food companies for offers and had the sponsor confirm that amount up front. Once the food was delivered on the day the sponsor pulled out the credit card and made all attendees happy by enabling them to making the blood sugar level catch up.

# Additional Info

In 2022 [Instana](https://www.instana.com/) sponsored the snacks. The snacks were ordered at Rewe

**Comment by timidak** [comment]
We (typedigital GmbH from Augsburg) would be very happy to sponsor the snacks on Saturday or Friday. ☺️ 
Just a quick question from our marketing team: They asked if snack sponsors would also be counted as normal sponsors, so if our logo would also be listed on the website and we would be allowed to bring a rollup and so on.

**Comment by meldron** [comment]
Hi @timidak,

awesome! Thanks a lot. 

> Just a quick question from our marketing team: They asked if snack sponsors would also be counted as normal sponsors, so if our logo would also be listed on the website and we would be allowed to bring a rollup and so on.

Yeah sure, there are no specific sponsor categories. 

Can you please provide a SVG image of your logo? I am planning to add the first wave of sponsors today or tomorrow, so would be nice if I can you folks too.

Thanks again!

**Comment by timidak** [comment]
Sounds great!

> Can you please provide a SVG image of your logo? I am planning to add the first wave of sponsors today or tomorrow, so would be nice if I can you folks too.

Sure ☺

![Image](https://user-images.githubusercontent.com/18395108/224716139-8c50e661-5697-47f7-9996-3a15aadd24bc.svg)

**Comment by timidak** [comment]
Hello again @meldron, 

we have some questions regarding the order of snacks:

1. we would like to order vegan snacks (e.g. hitschis, nuts, etc.), does that fit for you? Do you have any other recommendations?
2. should we get the snacks on our own in advance and bring them with us OR do you order the stuff and we just whip out our credit card for payment?

Thanks for your response, we're looking forward to meet you all!

**Comment by meldron** [comment]
Hi, just feel free to order them, vegan snacks sound awesome! If you can bring them to the venue yourself, I would prefer that solution, because then we don't need any more people in the loop.

If you have any other questions feel free to ask us.

Thanks again for stepping up!
