### ISSUE TITLE
Sponsor needed for Stickers - 💰

### ISSUE THREAD

**Issue by meldron** [jscraftcamp/website#1294]
# Why Stickers?
People love to have stickers, put them on their laptops, office, desk, etc. So let's give it to them.

# How does it work?
The costs are about 100,- Euro.
Ideally the sponsor aligns with the JSCraftCamp team via this issue here

1. what the stickers will look like
1. how many to order and
1. brings the stickers to the event
1. so they can be spread among all participants.

If you have any other wishes, as a sponsor, feel free to speak up. Use this issue here.

# Additional Info

In 2022  250 stickers were ordered at FlyerAlarm a couple of days (~4-5) before the event.

**Comment by MsAennaBanaena** [comment]
Mein [Arbeitgeber ](https://www.seppmed.de/) würde gerne das Stickersponsoring übernehmen. 

Lasst uns die Details gerne demnächst besprechen, dann leite ich alles weitere in die Wege!

**Comment by meldron** [comment]
Hey @MsAennaBanaena super! Wie würdest du die weitere Organisation am liebsten machen?

**Comment by MsAennaBanaena** [comment]
Lasst uns gerne einfach mal über Details sprechen! (Design, Stückzahl, Versand-Addy, Deadline... etc.)

**Comment by meldron** [comment]
Stickers were ordered at [Flyermeyer](https://flyermeyer.de/). 1000 outdoor Stickers, punched / uv protected, cost around ~250€.
