### ISSUE TITLE
Peerigon - Sponsor needed for Coffee, Barista ☕️ ☕️ ☕️ 🍵 - 💰💰💰

### ISSUE THREAD

**Issue by meldron** [jscraftcamp/website#1295]
# Why Coffee?

Many people want to have a coffee, especially in the morning when the open space starts many people crave for a coffee. But also after lunch many like to grab a coffee.

# How does it work?

Last year we had rented two coffee machines and cups from an external company. The coffee was prepared in two 10 liter "tanks", so we always had warm coffee.
If the sponsor for the coffee has a demand for a higher quality coffee or service, the attendees will definitely appreciate it.

# Additional Info

In 2022 [Peerigon](https://www.peerigon.com/de/) sponsored the coffee

**Comment by wolframkriesing** [comment]
inovex is interested

**Comment by meaku** [comment]
Hi @meldron @wolframkriesing! We – Peerigon – used to sponsor coffee and planned to do it again this year. Would you be up to swapping the sponsoring package? If not we'll pick something else, just wanted to ask as we have a working setup from last year that we could reuse.

**Comment by meldron** [comment]
Hi @meaku! I will ask inovex how flexible they are and get back to you. Thanks for stepping up again! 🎉

**Comment by Lisa-Giese** [comment]
> @meaku I talked with inovex, feel free to host/sponsor the coffee. They will take care of something else. Can you provide us with a logo (svg if possible)? Then I will add you to the list of sponsors on the website.
> 
> Thanks again for stepping up again! ❤️ 🎉

Hi @meldron, here is our logo as svg for the website. So happy to be coffee sponsor again :)
 
![Peerigon_Logo_RGB](https://user-images.githubusercontent.com/42241865/234790303-b4ddd0e6-f6df-44d7-ada7-1a08a3dd6245.svg)
