### ISSUE TITLE
(Optional?) Security for Corona and entrance check 💰💰💰💰💰

### ISSUE THREAD

**Issue by meldron** [jscraftcamp/website#1297]
# Why security and entrance check?
We want to make sure all attendees are as safe as possible at our event. Therefore, we decided to let everybody test negative for COVID-19 shortly before the event. To ensure the safety of us all, we want to have a security / entrance check for these test results.

# How does it work?
We have an offer from a security firm for under 500 € (+ taxes) for both days.

Let's try to be a non-spreading event and allow potentially vulnerable people into the sessions as well. There is a test center nearby to get official tests and if we make it mandatory to have a negative test result <24h, we should be as safe as possible.

**Comment by wolframkriesing** [comment]
looks like humanity has to learned living with corona ;)
