### ISSUE TITLE
Sponsor for the location - 💰💰💰💰💰

### ISSUE THREAD

**Issue by meldron** [jscraftcamp/website#1298]
We would like a location with the following properties:

* fits about 100 people
* has a couple of rooms
* has a big gathering space
* can be used Friday+Saturday
* (optional) party on Saturday in the location

Currently we are planing with CodeCentric.

**Comment by wolframkriesing** [comment]
Codecentric will host again. thanks!!! https://www.codecentric.de/

**Comment by marcoemrich** [comment]
[cc_PANTONE_big sign_CMYK_onWhite.pdf](https://github.com/jscraftcamp/website/files/11366770/cc_PANTONE_big.sign_CMYK_onWhite.pdf)
[CC_Pantone_onWhite.pdf](https://github.com/jscraftcamp/website/files/11366772/CC_Pantone_onWhite.pdf)
[cc_big sign_CMYK_onBlack.pdf](https://github.com/jscraftcamp/website/files/11366773/cc_big.sign_CMYK_onBlack.pdf)
[cc_big sign_CMYK_onWhite.pdf](https://github.com/jscraftcamp/website/files/11366774/cc_big.sign_CMYK_onWhite.pdf)
[cc_big sign_RGB_black.pdf](https://github.com/jscraftcamp/website/files/11366775/cc_big.sign_RGB_black.pdf)
[cc_big sign_RGB_onBlack.pdf](https://github.com/jscraftcamp/website/files/11366776/cc_big.sign_RGB_onBlack.pdf)
[cc_big sign_RGB_onWhite.pdf](https://github.com/jscraftcamp/website/files/11366777/cc_big.sign_RGB_onWhite.pdf)
[cc_big sign_white.pdf](https://github.com/jscraftcamp/website/files/11366778/cc_big.sign_white.pdf)
[CC_CMYK_black.pdf](https://github.com/jscraftcamp/website/files/11366779/CC_CMYK_black.pdf)
[CC_CMYK_onBlack.pdf](https://github.com/jscraftcamp/website/files/11366780/CC_CMYK_onBlack.pdf)
[CC_CMYK_onWhite.pdf](https://github.com/jscraftcamp/website/files/11366781/CC_CMYK_onWhite.pdf)
[CC_Pantone_onWhite.pdf](https://github.com/jscraftcamp/website/files/11366782/CC_Pantone_onWhite.pdf)
[CC_RGB_black.pdf](https://github.com/jscraftcamp/website/files/11366783/CC_RGB_black.pdf)
[CC_RGB_onBlack.pdf](https://github.com/jscraftcamp/website/files/11366784/CC_RGB_onBlack.pdf)
[CC_RGB_onWhite.pdf](https://github.com/jscraftcamp/website/files/11366785/CC_RGB_onWhite.pdf)
[CC_RGB_white.pdf](https://github.com/jscraftcamp/website/files/11366786/CC_RGB_white.pdf)
[cc_big sign_black.pdf](https://github.com/jscraftcamp/website/files/11366787/cc_big.sign_black.pdf)
