### ISSUE TITLE
Sponsor needed for Beverages 🍼🍹🥛🍵🍻 - 💰💰💰💰💰

### ISSUE THREAD

**Issue by meldron** [jscraftcamp/website#1301]
# Why Drinks?
The human body is made out of 90% of water - a good reason to always stay hydratred. For a developer, it might only be 70% water and 20% coffee (which https://github.com/jscraftcamp/website/issues/1074). Still: we need some nice beverages for our guests to stay fluid. Help us by either sponsoring the drinks completely or let us help you with a selection we like!

# How does it work?
Cost are around 500,- Euro.
Ideally the sponsor orders drinks that get delivered to the location. Feel free to ping us here in this ticket about past experience of what and how much to order.

Last year we ordered the amount of drinks we thought will be enough. The cool thing is that most companies also take back the bottles that had not been opened yet. The bill will be sent to the sponsors address afterwards.

# Additional Info

In 2022 [TNG](https://www.tngtech.com/) sponsored the following Beverages (except Water which was provided by the host Codecentric)

* cola
* mate
* schorlen
* beer

**Comment by githubjakob** [comment]
My company [Project Lary ](https://project-lary.com/) agreed to sponsor drinks.

**Comment by meldron** [comment]
Thanks @githubjakob! Looking forward to seeing you there!

**Comment by githubjakob** [comment]
Cool! @meldron should we have a talk end of May to check in what I need to organize?

**Comment by meldron** [comment]
Yeah that would be great. I sent you a message on Linkedin about contact information, we could also of course use the [discord](https://discord.gg/3mHhaXVEjP).

Thanks a lot!
