### ISSUE TITLE
Contact potential sponsors

### ISSUE THREAD

**Issue by meldron** [jscraftcamp/website#1313]
# Please pick/Ideas:
- [ ] Jetbrains
- [ ] MGM technology
- [ ] ~~Google münchen~~ ❌
- [ ] Allianz

## Wolfram
- [x] scalable capital (Wolfram via LinkedIn)
- [x] maibornwolff (Wolfram via LinkedIn)
- [x] mayflower
- [ ] methodpark
- [x] TNG ✔️
- [x] jambit ✔️
- [x] Pro7 (asked Tobi)
- [x] ~~github (in the talks)~~ ❌

## Joern
- [x] ~~grollmus~~ not this year ❌
- [x] peerigon ❓
- [x] alm+entwicklerstube ❓
- [x] Personio (asked through LinkedIn, waiting) ❓
- [x] celebrate company (asked through LinkedIn, waiting) ❓
- [x] ~~compose.us~~ ❌
- [x] Vercel (asked through email, waiting) ❓

## Robert
- [ ] hetzner
- [x] codecentric
- [x] GitPod

## Bernd
- [x] inovex ✔️
- [ ] xitaso (asked known contact, waiting for feedback) ❓
- [x] seppmed (asked known contact, waiting for feedback) ✔️
- [x] ~~Microsoft münchen~~ ❌

 ## Marco
- [x] datev
- [x] innoq
- [x] BSH

**Comment by wolframkriesing** [comment]
Hallo <Vorname>,
Gute Nachrichten: Das JSCraftCamp findet auch dieses Jahr wieder statt: am 30.Juli/1.Juli! Vor-Ort und mit echten Menschen:[ https://www.jscraftcamp.org/](https://www.jscraftcamp.org/)
Wir schreiben Dich bzw. Euch an, weil ihr uns in der Vergangenheit schon als Sponsor unterstützt habt. Auch dieses Jahr haben wir wieder verschiedene Sponsor-Items (https://github.com/orgs/jscraftcamp/projects/5) in unterschiedlichen Preisbereichen zur Verfügung und würden uns sehr freuen, wenn ihr wieder dabei wärt.
Hier ein paar der Möglichkeiten/Benefits:
Bis zu 3 vorregistrierte Teilnehmerplätze für Vertreter
Logo und Link auf der JSCraftCamp-Website
Euer Firmenname wird während der Konferenz mehrfach erwähnt
Es ist ein OpenSpace - bringt Vorträge, die euch wichtig sind, in die Community
Sponsoren werden über den offiziellen JSCC-Twitter-Account bekannt gegeben
Euer Aufsteller auf dem Event sorgt für Sichtbarkeit
Hängt Jobangebote an die Litfaßsäule, wo 80 hochmotivierte Entwickler einen Blick darauf werfen können
Wir freuen uns auch dieses Jahr wieder von Euch zu hören,
Marco & das JSCraftCamp-Orga-Team

**Comment by meldron** [comment]
* [x] inovex ✔️
* [ ] xitaso (asked known contact, waiting for feedback) ❓
* [ ] seppmed (asked known contact, waiting for feedback) ❓

**Comment by wolframkriesing** [comment]
hey @davelosert what about github sponsoring this event ... you remember ;)

**Comment by lowsky** [comment]
did not had any email for hetzner, so added them via GH handle, see https://github.com/jscraftcamp/website/issues/1362#issuecomment-1529068588
