### ISSUE TITLE
Add meta tags to website, for nice preview (in social media)

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#1323]
See e.g. https://twitter.com/JSCraftCamp/status/1626139539608567808
there is no preview yet

<img width="551" alt="image" src="https://user-images.githubusercontent.com/217931/224003689-9057accd-d311-43ac-a513-6b174cdacfbc.png">

**Comment by meldron** [comment]
```html
<!-- Open Graph / Facebook -->
<meta property="og:type" content="website" />
<meta property="og:url" content={Astro.url} />
<meta property="og:title" content={title} />
<meta property="og:description" content={description} />
<meta property="og:image" content={new URL(image, Astro.url)} />

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image" />
<meta property="twitter:url" content={Astro.url} />
<meta property="twitter:title" content={title} />
<meta property="twitter:description" content={description} />
<meta property="twitter:image" content={new URL(image, Astro.url)} />
```

**Comment by lowsky** [comment]
Automatically add the SEO headers

https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-seo-component

**Comment by lowsky** [comment]
@wolframkriesing , I will check if the gatsby thing  ^ already solves it, so that the new logo will be places correctly in the news ... WDYT?

I guess something was lost in the last years while updating 🙈

**Comment by lowsky** [comment]
^ Now I found the simplest solution, @wolframkriesing:
It seems to be missing the "image - link" in its header section:
https://github.com/jscraftcamp/website/blob/0bf5d40e096db8b96e26e48a4e8e5f3f6df9216a/src/components/page/page.js#L41-L70

**Comment by lowsky** [comment]
strange, @wolframkriesing , this still does not properly work on twitter:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/217931/224060819-532cdd05-3d19-43d0-adf8-c98ffcb31eac.png">

even after adding twitter:image ... with appropriate image url 🤷 
<img width="838" alt="image" src="https://user-images.githubusercontent.com/217931/224061125-bdf1aa2d-c986-4144-bc31-52b55faa3a5c.png">

**Comment by lowsky** [comment]
This seems to be solved now 

At least for twitter :-) 

<img width="598" alt="image" src="https://user-images.githubusercontent.com/217931/224164672-0ab0a9bc-6c62-4fbf-93b1-47e68c5b9962.png">
