### ISSUE TITLE
Can not upgrade project / fails on node-18

### ISSUE THREAD

**Issue by lowsky** [jscraftcamp/website#1332]
About 2 month ago, the netlify build was not able to run on node-18, and 
the only successful way was to freeze node version to v16.

To improve Developer Experience, let's fix the setup.

**Root Cause:**
Build failed because Gatsby used some old hashing function in its webpack build ,
which was rated insecure 😱:
```
1:23:07 PM: failed Building production JavaScript and CSS bundles - 15.235s
1:23:07 PM: error Generating JavaScript bundles failed
1:23:07 PM: Module build failed (from ./node_modules/gatsby/node_modules/css-loader/dist/cjs.js):

1:23:07 PM: Error: error:0308010C:digital envelope routines::unsupported

1:23:07 PM:     at /opt/build/repo/src/components/footer/footer.module.scss:1:1
```

P.S. this was also a blocker to migrate to Gatsby5 which depends on node-18 !

**Comment by lowsky** [comment]
With #1324 , storybook had to be disabled - as it was not able to build in GH action, e.g. 
https://github.com/jscraftcamp/website/actions/runs/4291244909
...

**Comment by Narigo** [comment]
I'm using a node:18 docker image and I can run the latest `main`. Is this done?

**Comment by lowsky** [comment]
Yea, @Narigo , you are right, this works again 👍
