### ISSUE TITLE
Design t-shirts

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#1371]

**Comment by Narigo** [comment]
@michaelzoidl how much can you help us with this?

We have currently said to add the location and the t-shirt sponsor to the shirt on the arms, we'd like to have the logo on the breast and the skyline on the back. Not sure how many shirts we need for the organizers this year yet, but we should add a clearly visible "ORGA" text for them, so people know who they can approach in case of event questions or code of conduct violations

**Comment by Narigo** [comment]
Here are the three shirt designs from Hetzner

![positionierung-JSCraftCamp](https://github.com/jscraftcamp/website/assets/1767865/f64b3d61-185c-4081-8ca5-f7af393c2b03)
![positionierung-JSCraftCamp-back](https://github.com/jscraftcamp/website/assets/1767865/6f2c59e5-293f-43f7-8510-c5e83464c85d)
![positionierung-JSCraftCamp-back-orga](https://github.com/jscraftcamp/website/assets/1767865/b540d77d-e13d-49fb-a7f1-377c3d6ee20e)
