### ISSUE TITLE
Create session notes repository

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#1372]
We should create a session notes repository and make sure to promote it, so people will upload their notes to the various sessions and other people have the chance to learn from them.

There should be a link to the past session notes as well.

**Comment by wolframkriesing** [comment]
ideas:
- find a session-note taker for every session
- add a checkbox in the registration "I will take session notes"

**Comment by Narigo** [comment]
https://github.com/jscraftcamp/jscc23-sessions
There is a `iCanTakeSessionNotes` flag in the registration now to show them in participants list

**Comment by lowsky** [comment]
repo exists. thx.
