### ISSUE TITLE
Receive and handle payment of snacks 🍿

### ISSUE THREAD

**Issue by Narigo** [jscraftcamp/website#1406]
See https://github.com/jscraftcamp/website/issues/1293 for the sponsor info

**Comment by Narigo** [comment]
Last time, we went downstairs and bought snacks from the Lidl (or whatever there was). That was actually a nice way of doing this and we used the payment receipt for that. Is this something we shall do again or do you want to have snacks done like lunch - way before the event?

**Comment by lowsky** [comment]
Something like the sponsoring last year where we just ordered in time from Rewe online?

**Comment by wolframkriesing** [comment]
done by #1586
