### ISSUE TITLE
compose.us - Sponsor for breakfast (Friday) 🥨🥪 💰

### ISSUE THREAD

**Issue by Narigo** [jscraftcamp/website#1557]
# Why breakfast?
Crafters arrive in the morning, to get the most out of the day. They had to wake up way too early for night owls and probably needed some time to get to the event itself. To put those morning grouches into a better mood, we'd like to offer them a little breakfast. A simple buffet can help to ignite some conversations between the first few people before the event itself begins.

# How does it work?
We need about 100,- (about 2,- pP, but we'd only buy breakfast for half of the participants - first come, first served)

Pretzels, Sandwiches and some sweet pastries should be ordered at a local bakery, to have them ready on the day of the event. The sponsor would need to go to bakery, collect and pay the order and should have them ready right when the doors open at 9:00am.

# Additional Info
There is a bakery right next to the codecentric building.

**Comment by cowglow** [comment]
Do we need a sub issue or a calendar event to remind us to pre-order?
