### ISSUE TITLE
Add hetzner as sponsor on the site and tweet

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#1589]
@meldron please provide 
- [x] if hetzner online or hetzner cloud is the sponsor and
- [x] their logo (hetzner cloud we do have already)
- [x] tweet them

thanks

**Comment by Narigo** [comment]
@wolframkriesing did JSCraftCamp tweet about Hetzner already? They are on the website as sponsor already.

**Comment by wolframkriesing** [comment]
https://twitter.com/JSCraftCamp/status/1672175048583520256
