### ISSUE TITLE
Add scalable as sponsor and tweet

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#1590]
- [x] Tweet with JSCraftCamp account
- [x] Add Scalable Capital to the website - see #1594

**Comment by wolframkriesing** [comment]
![Image](https://github.com/jscraftcamp/website/assets/113427/821ccc82-dba2-4efc-9084-ed370212ccf9)

**Comment by Narigo** [comment]
Website PR: #1594 - please tweet once merged!

**Comment by wolframkriesing** [comment]
is scheduled

**Comment by wolframkriesing** [comment]
https://twitter.com/JSCraftCamp/status/1672180695995944960
