### ISSUE TITLE
Contact sponsors

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#1816]
- [x] ✅ maibornwolff
- [x] ✅ TNG @wolframkriesing 
- [x] ✅ jambit @SS010  
- [x] ✅ inovex @meldron 
- [ ] codecentric @marcoemrich 
- [ ] ⌛ hetzner @wolframkriesing
- [x] ✅ peerigon @Narigo 
- [x] ✅ deno @crowlKats  
- [x] ✅ alm.engineering @michaelzoidl @Narigo @dreampulse 
- [ ] ⌛ aws @wolframkriesing 
- [x] ✅ Satellytes GmbH @wolframkriesing  [asked on linkedin, it worked](https://www.linkedin.com/feed/update/urn:li:activity:7183395519061245953?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7183395519061245953%2C7183443339260608512%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287183443339260608512%2Curn%3Ali%3Aactivity%3A7183395519061245953%29)
- [ ] typedigital 
- [ ] microsoft
- [ ] google
- [ ] ⌛ adesso @Narigo 
- [ ] adabay @SS010 
- [ ] exaring (waiputv) @SS010 
- [x] ❌ redmedical @SS010 
- [ ] eggsunimedia @SS010  
- [x] ❌ gitpod @lowsky
- [x] ❌ scalable @wolframkriesing (not this year, maybe next again)

**Comment by SS010** [comment]
@wolframkriesing I can not edit your list. Maybe I don't have the right permissions?

**Comment by wolframkriesing** [comment]
A email template, feel free to use and adapt

```
Hoffe Dir geht's gut. Ich melde mich im Auftrag des JSCraftCamp Orga teams.
Nun ist es mal wieder soweit, und ich wollte mal nachfragen, ob ??????? nicht wieder Lust hat etwas zu sponsorn beim JSCraftCamp?
Es gibt viele Optionen für viele Geldbeutel, die ihr gerne hier findet https://github.com/orgs/jscraftcamp/projects/7/views/1 

Als Sponsor sind natürlich auch Plätze für fünf eurer Personen reserviert und einiges anderes, Details
könnt ihr hier nachlese https://jscraftcamp.org/sponsoring/
Würde uns sehr freuen, wenn es dieses Jahr auch wieder klappt mit einem Sponsoring von ??????. 
Letztes Jahr kamen die Shirts ja echt gut an, soweit ich das mitbekam.
```

**Comment by Narigo** [comment]
Here is another e-mail that has been sent around by @marcoemrich:

```
Gute Nachrichten: Das JSCraftCamp ist zurück! Es wird am 17.05.2022 endlich wieder stattfinden! Vor-Ort mit echten Menschen: https://www.jscraftcamp.org/

Wir schreiben Euch an, weil ihr uns in der Vergangenheit schon als Sponsor unterstützt habt. Auch dieses Jahr haben wir wieder verschiedene Sponsor-Items (https://github.com/orgs/jscraftcamp/projects/7) in unterschiedlichen Preisbereichen zur Verfügung und würden uns sehr freuen, wenn ihr wieder dabei wärt.

Hier ein paar der Möglichkeiten/Benefits:

- Bis zu 3 vorregistrierte Teilnehmerplätze für Vertreter
- Logo und Link auf der JSCraftCamp-Website
- Euer Firmenname wird während der Konferenz mehrfach erwähnt
- Es ist ein OpenSpace - bringt Vorträge, die euch wichtig sind, in die Community 
- Sponsoren werden über den offiziellen JSCC-Twitter-Account bekannt gegeben
- Euer Aufsteller auf dem Event sorgt für Sichtbarkeit
- Hängt Jobangebote an die Litfaßsäule, wo 80 hochmotivierte Entwickler einen Blick darauf werfen können

Wir freuen uns auch dieses Jahr wieder von Euch zu hören,
Marco & das JSCraftCamp-Orga-Team
```
