### ISSUE TITLE
Sponsor needed for lunch on Friday 🍱 🍔 🍕 🌮 🍇

### ISSUE THREAD

**Issue by lowsky** [jscraftcamp/website#192]
## Why food?

No Food, no craftsmanship! Even the best people/coder need a full stomach - help us get some delicious energy-restorings for our guests. Of course as a sponsor you can either have a say in what to serve or you can leave it completely up to us to choose the right developers nutriment. And last year we got them all fed, so it's not as hard as it sounds :).

## How does it work?

Last year we asked some food companies for offers and had the sponsor confirm that amount up front. Once the food was delivered on the day the sponsor pulled out the credit card and made all attendees happy by enabling them to fill up their stomaches. And boy, they had been happier and their energy levels had been restored and they went for another half a day ... [until the party][party].

[party]: https://github.com/jscraftcamp/website/issues/201

**Comment by sportsracer** [comment]
TrustYou would love to sponsor lunch on Friday!

**Comment by wolframkriesing** [comment]
🎉 👍 🥇 
awesome ... I am happy to close the second sponsoring ticket!
Thank you Steffen and TrustYou for picking this up. Food is an important part for the event!!! yeah

**Comment by davelosert** [comment]
@sportsracer : I'd like to get in contact to clarify the details :smiley: 
Can you give me your E-Mail Address or just shoot me an E-Mail to david.losert@virtual-identity.com
