### ISSUE TITLE
Sponsor needed for lunch on Saturday 🍱 🍔 🍕 🌮 🍇

### ISSUE THREAD

**Issue by lowsky** [jscraftcamp/website#193]
## Why food?

No Food, no craftsmanship! Even the best people/coder need a full stomach - help us get some delicious energy-restorings for our guests. Of course as a sponsor you can either have a say in what to serve or you can leave it completely up to us to choose the right developers nutriment. And last year we got them all fed, so it's not as hard as it sounds :).

## How does it work?

Last year we asked some food companies for offers and had the sponsor confirm that amount up front. Once the food was delivered on the day the sponsor pulled out the credit card and made all attendees happy by enabling them to fill up their stomaches. And believe it or not, they had been happier and their energy levels had been restored and they went on for another half a day, learning and teaching.

**Comment by dpolivaev** [comment]
mercateo would like to become the Saturday lunch sponsor

http://www.mercateo.com/corporate

**Comment by wolframkriesing** [comment]
JIPPI. We have all attendees fed now. Thank you very much!!!

**Comment by davelosert** [comment]
@dpolivaev  : I'd like to get in contact to clarify the details :smiley: 
Can you give me your E-Mail Address or just shoot me an E-Mail to david.losert@virtual-identity.com
