### ISSUE TITLE
Sponsor needed for renting chairs 💺 💺 💺 💺 💺 💺 💺 💺

### ISSUE THREAD

**Issue by lowsky** [jscraftcamp/website#196]
## Why chairs?
We have a big hall and not enough chairs available in the office. In order for all people to have a seat while gathering in the center of the open space we need to rent chairs.

## How does it work?
Last year we contracted an external company, that was payed directly by the sponsor. We, the JSCraftCamp organizers, only organzied that the company delivers the right number of the chairs we wanted. Once they were delivered, the evening before the event volunteers set them up in the event space.

**Comment by wolframkriesing** [comment]
HolidayCheck will take that!!!
