### ISSUE TITLE
Sponsor needed for Coffee, Barista,  ... ☕️ ☕️ ☕️ ☕️ 

### ISSUE THREAD

**Issue by lowsky** [jscraftcamp/website#197]
## Why Coffee?
Many people want to have a coffee, especially in the morning when the open space starts many people crave for a coffee. But also after lunch many like to grab a coffee.

## How does it work?
Last year we had rented two coffee machines and cups from an external company. The coffee was prepared in two 10 liter "tanks", so we always had warm coffee.
If the sponsor for the coffee has a demand for a higher quality coffee or service, the attendees will definitely appreciate it.

**Comment by meaku** [comment]
We at [Peerigon](https://peerigon.com) love coffee and would like to sponsor some for the conference. I'm on vacation for a few days, so we can talk about the details next week.

**Comment by wolframkriesing** [comment]
@meaku that sounds like an awesome plan ... lets talk about details when you can :) #awesome

**Comment by meaku** [comment]
@wolframkriesing. We will definitely take care of coffee. 
We thought about brewed coffee all day long like last year, plus (maybe) an additional italian coffee machine for a few hours per day. Maybe for breakfast and after lunch depending on the costs. 

What do you think?

**Comment by wolframkriesing** [comment]
way cool! @meaku the coffee is all yours. For both days, right!?

**Comment by meaku** [comment]
>For both days, right!?

Sure! ☕️

**Comment by haslers** [comment]
Hi @meaku, I'm part of the organisation team. Do you have time for a quick phonecall/hangout/zoom meeting on friday or next week so we can quickly clarify a few points?

**Comment by meaku** [comment]
Wie wärs kommenden Dienstag? Da geht's bei mir generell ganz gut.

**Comment by haslers** [comment]
Passt bei mir. Ich kann da den ganzen Tag.

**Comment by meaku** [comment]
@wolframkriesing meinte dass virtual identity eine gute Siebträgermaschine vor Ort hat. Kann @davelosert dazu mehr sagen? Wir würden gern neben Filterkaffee auch morgens und Mittags für Barista style coffee sorgen.

**Comment by davelosert** [comment]
@meaku : Wir haben eine Siebträger-Maschine, allerdings halt nur eine sehr langsame und mit nur einem Auslauf. Das wird für 100 Leute vermutlich knapp werden. Wenn euch das aber reicht ist die Benutzung davon kein Problem.

Du kannst auch gerne mal vorbei schauen und sie die selber anschauen - meld dich einfach unter david.losert@virtual-identity.com :+1:
