### ISSUE TITLE
Sponsor needed for Beverages 🥛 🍵 🍺 

### ISSUE THREAD

**Issue by lowsky** [jscraftcamp/website#198]
## Why Drinks?

The human body is made out of 90% of water - a good reason to always stay hydratred. For a developer, it might only be 70% water and 20% coffee (which [we also search a sponsor for][coffee]). Still: we need some nice beverages for our guests to stay fluid. Help us by either sponsoring the drinks completely or let us help you with a selection we like!

## How does it work?

Last year we ordered the amount of drinks we thought will be enough. The cool thing is that most companies also take back the bottles that had not been opened yet. The bill will be sent to the sponsors address afterwards.

[coffee]: https://github.com/jscraftcamp/website/issues/197

**Comment by Narigo** [comment]
Do you remember the amount of last years bill, just to have a pointer on what to expect for a possible sponsor?

**Comment by lowsky** [comment]
@Narigo , thanks for your interest and your question: 
And after checking last years costs, we also adapted the value we had on our sponsoring page:

Last year, it was 430€, so 500€ might be enough, even it is summer 🌞 and people will drink more because of it will be hot 🌡  !

As stated above: we would used a provider who delivered "on commission", taking unused bottles back.

**Comment by wolframkriesing** [comment]
this will be handled by TNG
