### ISSUE TITLE
How do we handle coffee cups?

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#1980]
Maibornwolff does not have enough cups.
maybe bring your own cup?
recups, ???

**Comment by Lisa-Giese** [comment]
@wolframkriesing we will hire a barista who will bring cups. We are calculating with 50 people per day, 100 in total. Is that up to date? In addition we could bring some of our Peerigon cups as well.

**Comment by Narigo** [comment]
I think this is a duplicate of https://github.com/jscraftcamp/website/issues/1871 ?

**Comment by wolframkriesing** [comment]
closed as dup, see above
