### ISSUE TITLE
Sponsor needed for Stickers 🎫 🎫 🎫 🎫 

### ISSUE THREAD

**Issue by lowsky** [jscraftcamp/website#200]

**Comment by Hannahjambit** [comment]
Hi, we from jambit are interested in sponsoring JSCraftCamp. e.g. with stickers. what are these for stickers? Can you tell us?

**Comment by Hannahjambit** [comment]
what's the next step? what do we have to do? Looking forward to hearing from you. LG Hannah

**Comment by wolframkriesing** [comment]
Hi @Hannahjambit oh yeah ... cool.
The stickers are for all the attendees and those interested, to put on the laptop, phone ... or wherever stickers go :) last year we had two different sizes, the cost had been about 100,- ...
We would order them and redirect the bill to you. Sounds like a plan?

**Comment by wolframkriesing** [comment]
@Hannahjambit you can email me at wolfram and then kriesing.de

**Comment by Hannahjambit** [comment]
..and in exchange our logo and link will be posted on the webpage, right? on the stickers there is the name "JSCraftCamp"?? Thanks a lot.

**Comment by wolframkriesing** [comment]
all details about sponsoring are described in detail here http://jscraftcamp.org/sponsoring.html
thanks a lot for sponsoring!!!

**Comment by lowsky** [comment]
At least, on our web site it still states 'sponsor this' for the stickers: http://jscraftcamp.org/sponsoring.html

**Comment by Hannahjambit** [comment]
jambit will sponsor the stickers. I confirmed that last thursday and wrote with Wolfram. Wolfram closed #200

**Comment by Hannahjambit** [comment]
thanks lowsky for the info - who can change it on the web site into "sponsored by jambit"?
