### ISSUE TITLE
Sponsor needed for the Party Friday evening 🍺 🥂 🍸 🍾 🎼 🎉

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#201]
## Why a party?
At the end of the first day we want to throw a party. The location is perfect to also be outside (permitting weather) and we also don't have restrictions since there is nobody living close by. So the party can be open end :).
This year we moved the JSCraftCamp to take place in summer, which allows to make use of the garden surrounding the event space. And the Isar is close too, so this might be epic.

## Last year?
There was no party :(. We just met in a restaurant.

**Comment by admc** [comment]
S2 will be happy to sponsor the party, currently locking down final budget, approx $1500.

**Comment by wolframkriesing** [comment]
YEAH ... that will be a great party. Let's pray for some sun and the people will bring the fun! cu
Thank you very much
