### ISSUE TITLE
Sponsor needed for lunch on Friday

### ISSUE THREAD

**Issue by marcoemrich** [jscraftcamp/website#360]
## Why food?

No Food, no craftsmanship! Even the best people/coder need a full stomach - help us get some delicious energy-restorings for our guests. Of course as a sponsor you can either have a say in what to serve or you can leave it completely up to us to choose the right developers nutriment. And last year we got them all fed, so it's not as hard as it sounds :).

## How does it work?

Last year we asked some food companies for offers and had the sponsor confirm that amount up front. Once the food was delivered on the day the sponsor pulled out the credit card and made all attendees happy by enabling them to fill up their stomaches. And boy, they had been happier and their energy levels had been restored and they went for another half a day ... [until the party][party].

[party]: https://github.com/jscraftcamp/website/issues/367

**Comment by wolframkriesing** [comment]
Thanks to [TNG](https://www.tngtech.com/), Christoph Stock offered to sponsor the Friday Lunch!
thanks a lot!!!!
