### ISSUE TITLE
Sponsor needed for lunch on Saturday

### ISSUE THREAD

**Issue by marcoemrich** [jscraftcamp/website#361]
## Why food?

No Food, no craftsmanship! Even the best people/coder need a full stomach - help us get some delicious energy-restorings for our guests. Of course as a sponsor you can either have a say in what to serve or you can leave it completely up to us to choose the right developers nutriment. And last year we got them all fed, so it's not as hard as it sounds :).

## How does it work?

Last year we asked some food companies for offers and had the sponsor confirm that amount up front. Once the food was delivered on the day the sponsor pulled out the credit card and made all attendees happy by enabling them to fill up their stomaches. And believe it or not, they had been happier and their energy levels had been restored and they went on for another half a day, learning and teaching.

**Comment by wolframkriesing** [comment]
netcentric.biz is sponsoring this.

**Comment by marcoemrich** [comment]
Can we use this logo: https://www.netcentric.biz/content/dam/nc/logo/logo__regular.svg ?
