### ISSUE TITLE
Sponsor needed for snacks on Friday

### ISSUE THREAD

**Issue by marcoemrich** [jscraftcamp/website#362]
## Why Snacks?

Prevent a low blood sugar by providing quick energy refilling snacks in the form of sweets, baked goods and candy. Keep those hard working brains happy - either by choosing yourself what to get or just leave it up to us to find the right sugar-bombs!

## How does it work?

Last year we asked some food companies for offers and had the sponsor confirm that amount up front. Once the food was delivered on the day the sponsor pulled out the credit card and made all attendees happy by enabling them to making the blood sugar level catch up. 
And we tell you, they had will be happy ... [until they need more, at party at night][party].

[party]: https://github.com/jscraftcamp/website/issues/367

**Comment by jambit1** [comment]
Hi Marco! jambit is interested in sponsoring snacks on friday. let me know what the next steps are :)

**Comment by marcoemrich** [comment]
Hi. That's actually pretty easy :)

We just need your confirmation. When we have the location and date, we inform you, so that you can organize snacks. You can pay directly to the seller(s). Maybe someone from Jambit is will even be on site.

We would need fruits and sweets for about 100 people. Last year this took about ~100€. But it's up to you, how much you are willing to spend.

I can also put your logo (can we use the one from last year? http://jscraftcamp.org/img/sponsor-2017/jambit_logo.jpg) on the webpage, organize the sponsoring tweet and so on ...

**Comment by marcoemrich** [comment]
Great News! Thank you so much!

I already added you logo in PR https://github.com/jscraftcamp/website/pull/380. It just needs to be merged by someone else from the orga team.

**Comment by jambit1** [comment]
Hi @marcoemrich 

we will send sweets and fruits for ~100 people to 
Virtual Identity AG
Isarwinkel 16
81379 München

on the 10th of august or one day before?

thanks!

**Comment by marcoemrich** [comment]
I think delivering a day earlier shouldn't be an issue. I asked at VI, so we should get a definitive answer.
