### ISSUE TITLE
Sponsor needed for snacks on Saturday

### ISSUE THREAD

**Issue by marcoemrich** [jscraftcamp/website#363]
## Why Snacks?

The night before was a party. If the attendees don't need a snack now, they must have some other secret sauce to get their bodies back up to speed. But many rely on a sponsor to help out and prevent a low blood sugar by providing quick energy refilling snacks in the form of sweets, baked goods and candy. Keep those hard working brains happy - either by choosing yourself what to get or just leave it up to us to find the right sugar-bombs!

## How does it work?

Last year we asked some food companies for offers and had the sponsor confirm that amount up front. Once the food was delivered on the day the sponsor pulled out the credit card and made all attendees happy by enabling them to making the blood sugar level catch up.

**Comment by AnianZ** [comment]
Hey Marco,
we are a Start-Up from Augsburg and want to ensure the blood sugar supply for the attendees of the JSCraftCamp.
Please [get in touch with me](mailto:r.koch@cioplenu.de) to steer the sponsoring properly

**Comment by wolframkriesing** [comment]
Awesome! Thanks for sponsoring the JSCraftCamp.
Oh that sounds cool. Can you please give us a link to your company name and logo, so we can put it on the website.

**Comment by AnianZ** [comment]
Sure @wolframkriesing . You can find out more about cioplenu under https://cioplenu.com/. Logo files for the website can be found [here](https://cloud.sicony.de/s/y42TBWGnfcMZY5d)

**Comment by wolframkriesing** [comment]
sponsor found, the next steps are handled in 
https://github.com/jscraftcamp/website/issues/498 by the JSCC crew. thanks
