### ISSUE TITLE
Sponsor needed for Coffee, Barista, ... ☕️ ☕️ ☕️ ☕️

### ISSUE THREAD

**Issue by marcoemrich** [jscraftcamp/website#364]
## Why Coffee?
Many people want to have a coffee, especially in the morning when the open space starts many people crave for a coffee. But also after lunch many like to grab a coffee.

## How does it work?
Last year we had rented two coffee machines and cups from an external company. The coffee was prepared in two 10 liter "tanks", so we always had warm coffee.
If the sponsor for the coffee has a demand for a higher quality coffee or service, the attendees will definitely appreciate it.

**Comment by meaku** [comment]
Peerigon is interested in sponsoring coffee! We'll discuss it internally and keep you updated ☕️ ☕️ ☕️
