### ISSUE TITLE
Sponsor needed for Beverages

### ISSUE THREAD

**Issue by marcoemrich** [jscraftcamp/website#365]
## Why Drinks?

The human body is made out of 90% of water - a good reason to always stay hydratred. For a developer, it might only be 70% water and 20% coffee (which [we also search a sponsor for][coffee]). Still: we need some nice beverages for our guests to stay fluid. Help us by either sponsoring the drinks completely or let us help you with a selection we like!

## How does it work?

Last year we ordered the amount of drinks we thought will be enough. The cool thing is that most companies also take back the bottles that had not been opened yet. The bill will be sent to the sponsors address afterwards.

[coffee]: https://github.com/jscraftcamp/website/issues/364

**Comment by uuzaix** [comment]
Hi Marco,

Futurice would be happy to sponsor Drinks for JSCraftCamp. Please let me know what should we provide for that.

Regards,
Larisa

**Comment by michaelzoidl** [comment]
Hey @marcoemrich and @uuzaix,
the entwicklerstube can give a bonus and sponsor 10 boxes of club mate :) I can take it with me when I come on Friday.

**Comment by marcoemrich** [comment]
Hi Larisa (@uuzaix),

thanks for sponsoring! And sorry for my late answer. Your colleague Andreas already works with @lowsky on the issue. If you need anything else don't hesitate to ask.

thanks,
Marco

**Comment by marcoemrich** [comment]
Hey Michi (@michaelzoidl ),

Thanks a lot! Can you send me a logo, I can integrate on the website? Do you need anything else?

thanks,
Marco

**Comment by michaelzoidl** [comment]
Hey Marco
I didn't know what format and dimensions you needed so I orientated myself on the codecentric logo. I didn't know the format either, so I've prepared several for you. :)

**SVG**
https://entwicklerstube.com/storage/media/banner.svg

**JPEG**
https://entwicklerstube.com/storage/media/banner.jpg
https://entwicklerstube.com/storage/media/banner@2x.jpg

**PNG**
https://entwicklerstube.com/storage/media/banner.png
https://entwicklerstube.com/storage/media/banner@2x.png

**Comment by lowsky** [comment]
Hi Larisa (@uuzaix),

It is great, to have Futurice sponsor the Drinks for JSCraftCamp!

Can you also send us the logos for integration on our sponsor page?

Regards,
Larisa

**Comment by uuzaix** [comment]
Hi Robert,

Here is Futurice logo in png format - 

![futurice_logo](https://user-images.githubusercontent.com/10480576/43122345-f98d58ae-8f20-11e8-8cd4-283abbb6c081.png)

Please let me know if you need it in different formats or sizes.

**Comment by wolframkriesing** [comment]
logos added
https://github.com/jscraftcamp/website/pull/478/commits/42a380b9f9f86b26f2f0f4ea71978e5c548b87a4

**Comment by wolframkriesing** [comment]
afaik this is done, sponsor found.
the rest will be handled by JSCC crew (in here 
https://github.com/jscraftcamp/website/issues/497)
