### ISSUE TITLE
Sponsor needed for the Party Friday evening

### ISSUE THREAD

**Issue by marcoemrich** [jscraftcamp/website#367]
## Why a party?
At the end of the first day we want to throw a party

If the party has music, BBQ or just drinks is up to the sponsor. We would like to have a party and leave it to those bringing the money what can be afforded, of course we help organizing if wanted.

## Last year?
We had an epic party at Virtual Identity using the garden surroundings and the event space. We had a BBQ, music, cold drinks, etc ...

**Comment by wolframkriesing** [comment]
pro 7 is doing it ... yeah!

**Comment by wolframkriesing** [comment]
done
next steps handled by JSCC crew, trackable via #495 and #496
