### ISSUE TITLE
Sponsor needed for Stickers [TODO Description missing]

### ISSUE THREAD

**Issue by marcoemrich** [jscraftcamp/website#368]

**Comment by MsAennaBanena** [comment]
Hallo! Unsere Firma (Method Park) würde gerne das Sticker-Sponsoring übernehmen. 
Ihr könnt euch gerne auch per Mail melden: anna.zeidler@methodpark.de 

Herzliche Grüße
Anna

**Comment by marcoemrich** [comment]
Hallo Anna,

herzlichen Dank für das Angebot! Das nehmen wir gerne an. Im Grunde brauchen wir nur

 * eure Zusage

 * das Budget, was wir maximal dafür ausgeben dürfen (bei den Stickern hatten wir ca. 100 € vorgesehen)

 * und eure Rechnungsadresse

Wir lassen die Rechnung dann direkt an euch senden.

Außerdem wäre es hilfreich, wenn Du mir das Method Park-Logo als PNG oder JPG schicken könntest. Dann packen wir es gleich auf die Website.

vielen herzlichen Dank,

Marco und das JSCraftCamp-Team

**Comment by MsAennaBanaena** [comment]
Hi Marco, 

super, dass das klappt. :-)
Die Zusage bekommst du hiermit von mir. 
Das Budget liegt bei 150-200 Euro. 

Rechnungsadresse:
Method Park Holding AG
Anna Zeidler
Wetterkreuz 19a 
91058 Erlangen 

![rs318_rs12_method_park_logo- 21](https://user-images.githubusercontent.com/40165724/41406643-36d09500-6fcd-11e8-8208-b4dd2955881c.png)

Schickst du auch Bilder der Sticker und des Camps? 
Twitter: @methodpark_DE 

Wenn Du noch etwas brauchst, melde Dich gerne bei mir. 

Alles Liebe und eine tolle Veranstaltung,
Anna

**Comment by wolframkriesing** [comment]
@MsAennaBanaena these are the stickers for this year
https://github.com/jscraftcamp/logo/blob/master/ordered/2018/JSCraftCamp-Sticker.pdf

the receipt is issued to the address you posted above. Thanks a lot for your support!
