### ISSUE TITLE
Enable HTTPS for the page

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#372]
https://jscraftcamp.org brings up a warning now

**Comment by andys8** [comment]
There is a blog post from a week ago, mentioning GitHub pages is now supporting "let's encrypt".

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by wolframkriesing** [comment]
<img width="693" alt="bildschirmfoto 2018-05-08 um 18 29 16" src="https://user-images.githubusercontent.com/113427/39769897-c593f1bc-52ed-11e8-8f76-5741e1d6489b.png">

who knows what that means?

**Comment by andys8** [comment]
I have no idea, but people in this thread were discussing and re-adding the domain solved issues for some of them.

https://github.community/t5/Pages/How-to-enable-https-support-on-custom-domains/td-p/6894

**Comment by wolframkriesing** [comment]
mmmh, i tried it in any order ... i am out of patience right now :)

**Comment by FQ400** [comment]
Could this be helpful: https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by coderbyheart** [comment]
Yes, enabling HTTPs for the website will generate a new certificate and it will be available after a while.
I use this e.g. to serve https://paulaner.hiv 

![screenshot-2019-06-01T231152](https://user-images.githubusercontent.com/188915/58753665-38538e80-84c3-11e9-8086-ff8172b690ae.png)

**Comment by wolframkriesing** [comment]
i tried it again, removed the domain and added it again ... waiting

**Comment by coderbyheart** [comment]
I did not work, however looking at the DNS records, I see that jscraftcamp.org does not have to proper A records, as outlined here: https://help.github.com/en/articles/setting-up-an-apex-domain

```
dig +noall +answer jscraftcamp.org
jscraftcamp.org.        86260   IN      A       151.101.12.133
```

For SSL to work, the domain needs to point to GitHub IPs:

185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153

**Comment by Narigo** [comment]
https is working since a while now. We can close this 🎉
