### ISSUE TITLE
additional GDPR issues

### ISSUE THREAD

**Issue by marcoemrich** [jscraftcamp/website#391]
* Google Fonts (turn off)
 * Font Awsome
 * Datenschutzbestimmungen Wizard
 * Github host erklärung
 * Github Cookie

**Comment by marcoemrich** [comment]
see https://github.com/jscraftcamp/website/pull/394

**Comment by marcoemrich** [comment]
The privacy policy still needs a review. Also: maybe we should completely remove the participants page.

**Comment by lowsky** [comment]
Btw. Additionally we may also need the agreement of each attendee that photos can be taken.

**Comment by lowsky** [comment]
The content looks good, in my opinion.
We could defer the part of the registration, discuss it and make it clear when the registration opens
