### ISSUE TITLE
Sponsor needed for renting chairs 💺 💺 💺 💺 💺 💺 💺 💺

### ISSUE THREAD

**Issue by marcoemrich** [jscraftcamp/website#393]
## Why chairs?
We have a big hall and not enough chairs available in the office. In order for all people to have a seat while gathering in the center of the open space we need to rent chairs.
We will also need some benches (Bierbaenke) for sitting outside.
Estimated cost ~300 Euro.

## How does it work?
Last year we contracted an external company, that was payed directly by the sponsor. We, the JSCraftCamp organizers, only organzied that the company delivers the right number of the chairs we wanted. Once they were delivered, the evening before the event volunteers set them up in the event space.

The payment will be done by the sponsor directly to the company where we rent the chairs from. We will put you in contact and you (the sponsor) can handle it from that point on.

**Comment by johannes-weber** [comment]
Mayflower would love to sponsor this package. How to proceed further?

**Comment by wolframkriesing** [comment]
@johannes-weber I updated the description above, to tell you about the payment process. Any further questions?

**Comment by johannes-weber** [comment]
Thanks - no further questions anymore!

**Comment by lowsky** [comment]
Hi @johannes-weber! 
Great, so I am assuming we can put the Mayflower logo on our sponsors page.

Can you provide a picture with your logo?

**Comment by lowsky** [comment]
Hi @johannes-weber! 
Great, so let's add Mayflower on our sponsors page.
Can you provide an image of the logo?

**Comment by wolframkriesing** [comment]
done, thx Mayflower,
further handling will be done by JSCC crew, trackable via #494 if interested
