### ISSUE TITLE
Order drinks for Friday evening party [sponsored by Pro7]

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#496]
What is there to do?
- [x] create list of what drinks to order (maybe take experience from last years into account)
- [x] order the beverages for friday evening party, see #367 
- [x] make sure they arrive at the location, receive them (or delegate to somene to do so)
- [x] ensure that the sponsor's address will be on the bill, watch out if you order all drinks (also for the event together, you need to split the bill)
- [ ] tell sponsor about the incoming invoice

**Comment by Narigo** [comment]
I guess all of the past years invoicing stuff has been done already. I'll close this 💸
