### ISSUE TITLE
Order beverages for the event [sponsored by futurice]

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#497]
What is there to do?
- [x] create list of what drinks to order (maybe take experience from last years into account)
- [x] order the beverages for both days of the event, see #365 
- [x] make sure they arrive at the location, receive them (or delegate to somene to do so)
- [x] ensure that the sponsor's address will be on the bill
- [ ] tell sponsor about the incoming invoice

**Comment by Narigo** [comment]
2018 invoices should have been done 💸
