### ISSUE TITLE
Sponsor needed for renting chairs, beer benches, cuttlery 🍴🍴🍴💺 💺 💺  - 💰💰💰

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#537]
## Why chairs?
We have a big hall and not enough chairs available in the office. In order for all people to have a seat while gathering in the center of the open space we need to rent chairs.
We will also need some benches (Bierbaenke) for sitting outside.
Estimated cost ~300 Euro.

## How does it work?
Last year we contracted an external company, that was payed directly by the sponsor. We, the JSCraftCamp organizers, only organzied that the company delivers the right number of the chairs we wanted. Once they were delivered, the evening before the event volunteers set them up in the event space.

The payment will be done by the sponsor directly to the company where we rent the chairs from. We will put you in contact and you (the sponsor) can handle it from that point on.

**Comment by s1hofmann** [comment]
/me is raising his on this one.

**Comment by wolframkriesing** [comment]
awesome @s1hofmann I moved the ticket into "sponsor found" 
nice! thanks a lot
see this board https://github.com/jscraftcamp/website/projects/7

**Comment by ZNicoZ** [comment]
Do you need more than one sponsor for this? (it is still shown as "open" on your [website](http://jscraftcamp.org/sponsoring.html))

**Comment by marcoemrich** [comment]
Ah no - it just wasn't updated on the website.

Saturday Snacks and Friday Party is still open!

**Comment by lowsky** [comment]
Hi Simon, @s1hofmann, great. 

Can you additionally provide a logo for the sponsor page? thx.

**Comment by s1hofmann** [comment]
Hi @lowsky,

sorry for the delay, here’s the logo attached:

![ConSol-Logo-Deutsch-Claim-RGB](https://user-images.githubusercontent.com/7813765/56881823-f8cbf980-6a61-11e9-9af9-fcee1f1c29e8.png)

Looking forward to JSCC19 :)
