### ISSUE TITLE
Sponsor needed for lunch on Friday 🍱 🍔 🍕 🌮 🍇 - 💰💰💰💰💰💰💰💰💰

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#538]
## Why food?

No Food, no craftsmanship! Even the best people/coder need a full stomach - help us get some delicious energy-restorings for our guests. Of course as a sponsor you can either have a say in what to serve or you can leave it completely up to us to choose the right developers nutriment. And last year we got them all fed, so it's not as hard as it sounds :).

## How does it work?

We need about 800,- (8,- pP)

Last year we asked some food companies for offers and had the sponsor confirm that amount up front. Once the food was delivered on the day the sponsor pulled out the credit card and made all attendees happy by enabling them to fill up their stomaches. And boy, they had been happier and their energy levels had been restored and they went for another half a day ... [until the party][party].

[party]: https://github.com/jscraftcamp/website/issues/201

**Comment by martinlechner1** [comment]
Hi,
Scout24 can most likely take care about lunch sponsorship. Could you contact me via mail: martin.lechner@scout24.com
Best,
Martin

**Comment by c-stoeckl** [comment]
Hi! :)
Since you moved this to in discussion again:
If you are still looking for a food sponsor we (Hetzner Cloud) would also be happy to take care of this.

**Comment by wolframkriesing** [comment]
@c-stoeckl awesome that you ping us, thanks a lot. Oh yes, we are looking for a sponsor for this again. We would love to have Hetzner Cloud take this.

**Comment by wolframkriesing** [comment]
@c-stoeckl can you please provide the logo we can use on the website, ideally it should have a transparent background
