### ISSUE TITLE
Move site to netlify

### ISSUE THREAD

**Issue by jurekbarth** [jscraftcamp/website#544]
Custom build process. Working Https out of the box :)

**Comment by lowsky** [comment]
Besides the hosting on netlify we will then need to link to netlify privacy informations!
* https://www.netlify.com/privacy/
* see also https://www.netlify.com/gdpr/

/cc @marcoemrich

**Comment by Narigo** [comment]
I guess the website will continue to live on github pages as everything else is done there as well. @lowsky if you have any objections, please reopen this! :octocat:
