### ISSUE TITLE
Items collected after the orga retro

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#545]
The following are the items we had collected during our organization-retro after the event.
If you want/can to pick anything off the list and work it off before the next event feel free ... otherwise we will convert the items into issues around Jan 2019 in order to work them off.

- [ ] microphone would be helpful, hard to understand on the stairs, or more chairs to not sit on the stairs
- [ ] order drinks to arrive 2 days before, to be sure they arrive early
- [ ] order food the week before the event
- [ ] order a second grill
- [ ] add "jobs to do" to the website
- [x] turn off tshirt field when registration is too late
- [ ] chart that shows the registrations
- [x] link  joerns repo (@Narigo/jscc18 ?!) on the website
- [x] wifi setup at location
- [ ] welcome board at the location (as we had it), set it up
- [ ] generate tweets from participants input (use tags, interest, contribute fields)
- [ ] setup twitter wall at the event location
- [ ] announce evening activities, board games, etc. ... add it to schedule
- [ ] campfire (Feuerschale) 
- [x] have budget of 800 for lunch (not pizza)
- [x] change dietary to boolean: vegan, vegetarian and string field "allergies"
- [x] finish the party order the day before the event
- [x] set milestones for when what has to be done
- [x] visualize the milestones on the website, so people see when there are deadlines for shirt ordering, food ordering, etc.
- [x] put the prices for the sponsor items in the issues not only on the sponsoring page
- [x] add date for sitting together for 1st time to find event date, e.g. January - 18th January 14:30
- [x] how can we find out the no-show rate? use the nametags to count the no-show rate, print them out for  every day (in different color/shape) and all that are left are no-shows
- [x] invite Cecilia again
- [x] book rooms long before (Virtual Identity)
- [x] let community determine the color for JSCC19

**Comment by Narigo** [comment]
Added all of these things to the best practice wiki page: https://github.com/jscraftcamp/website/wiki/Best-Practices-&-Reviews
