### ISSUE TITLE
Find out if Virtual Identify wants to host us again in 2019

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#551]

**Comment by SheepFromHeaven** [comment]
@lowsky Virtual Identity will host again. We also have a big summer party around that month, so we should get to setting a date asap 😄

**Comment by wolframkriesing** [comment]
@SheepFromHeaven woohoo, that sounds awesome. We thought of July, do you have any Friday+Saturday available in July. If you let us know soon we can announce it and start organizing.

**Comment by lowsky** [comment]
🛎 Hi @SheepFromHeaven can you already tell us which days would be possible, so we can make the decision?

**Comment by SheepFromHeaven** [comment]
@lowsky I just need to wait until (i hope) next week for the decision, when the summer party will be.
