### ISSUE TITLE
Sponsor needed for Beverages 🍼🍹🥛🍵🍻 - 💰💰💰💰💰

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#561]
## Why Drinks?

The human body is made out of 90% of water - a good reason to always stay hydratred. For a developer, it might only be 70% water and 20% coffee (which [we also search a sponsor for][coffee]). Still: we need some nice beverages for our guests to stay fluid. Help us by either sponsoring the drinks completely or let us help you with a selection we like!

## How does it work?

Cost are around 500,- Euro.
Ideally the sponsor orders drinks that get delivered to the location. Feel free to ping us here in this ticket about past experience of what and how much to order.
 
Last year we ordered the amount of drinks we thought will be enough. The cool thing is that most companies also take back the bottles that had not been opened yet. The bill will be sent to the sponsors address afterwards.

[coffee]: https://github.com/jscraftcamp/website/issues/558

**Comment by lowsky** [comment]
I have asked @andunion for sponsoring by adding some bottles of their tasty **crafts**beer. (currently waiting for response)

**Comment by MsAennaBanaena** [comment]
We want your guests to stay fluid. :) We are interested in sponsoring the 500 Euro for the beverages. :)

**Comment by marcoemrich** [comment]
Awesome! Thank you! 

Can you send us a current logo of Methodpark, so we can list you as Sponsor on jscraftcamp.org?

Is there any thing else you need to know? You can also contact me by email marcoemrich77@googlemail.com or the whole team with team@jscraftcamp.org.

**Comment by MsAennaBanaena** [comment]
Sounds great... Thank you!! It's great to be a part of it again. :) I'll write you an email... :)
