### ISSUE TITLE
Contact last year's sponsors, ask if they want to sponsor again

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#570]
_checked means (at least) already asked, the actual progress will be in the Sponsoring2019 project._

* [x] Pro7 Sat1 Media
* [x] SinnerSchrader
* [x] codecentric
* [x] Entwicklerstube
* [x] Jambit
* [ ] Netcentric
* [x] Peerigon
* [ ] Futurice
* [x] Methodpark
* [x] TNG
* [x] Mayflower
* [x] cioplenu

**Comment by marcoemrich** [comment]
I start to collect the email addresses and names of contact persons. Please feel free to add any data you have in the ticket.

**Comment by lowsky** [comment]
@wolframkriesing haven't you already asked Netcentric and Futurice already? Can this issue be closed?
