### ISSUE TITLE
Order a second grill

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#572]
e.g. here https://www.seidel-in-solln.de/grillverleih/

**Comment by lowsky** [comment]
https://jscraftcamp.slack.com/archives/G43KGJ49W/p1562831987000200

**Comment by lowsky** [comment]
https://jscraftcamp.slack.com/archives/G43KGJ49W/p1562831987000200

**Comment by Narigo** [comment]
Last year, should be closed ✅
