### ISSUE TITLE
Advertise for session notes

### ISSUE THREAD

**Issue by Narigo** [jscraftcamp/website#666]
It would be nice to have notes about the sessions, so one can read them and learn from it afterwards. There are a lot of links, frameworks, libraries, general tech to look at, when heading home. I struggle to remember these things, so I've tried to keep notes and share it with others. A few people helped by contributing their notes to the repository on my private account (https://github.com/Narigo/jscc18).

Would be great to have something more "official" and promote that repository through the website and during the intro / retro sessions.

If you want, I can maintain that repository (i.e. create the schedule table, merge pull requests of peoples notes, etc.).

**Comment by marcoemrich** [comment]
That is awesome! I'm all for making it official!

**Comment by marcoemrich** [comment]
@Narigo what would be a good place on the website to promote it?

**Comment by Narigo** [comment]
I think a paragraph near the schedule would make sense. A suggestion:

> **Take notes!**
> If you participate in a session, it's always good to write down notes. It helps you keep track of all the information you receive, you will remember the name of the new tech that was mentioned and maybe the session owner shares some slides online. For additional fame and bonus points from your peers, share your notes [in the official repository for session notes](https://github.com/jscraftcamp/jscc19-sessions)!

**Comment by marcoemrich** [comment]
Hey Joern

I created a PR https://github.com/jscraftcamp/website/pull/684 and the Repo
https://github.com/jscraftcamp/jscc19-sessions

you have admin-Rights

thanks for the idea!
Marco

**Comment by Narigo** [comment]
I'll close this since #684 is merged and visible on the website :)
Thanks!
