### ISSUE TITLE
Subdomain for session notes

### ISSUE THREAD

**Issue by Narigo** [jscraftcamp/website#798]
Hi there, the session notes is now using docsify and is currently here: https://jscraftcamp.github.io/jscc19-sessions

If you could add a subdomain like notes2019.jscraftcamp.org we could add a CNAME to the session notes repository and have something more connected to the jscraftcamp.org site.

**Comment by wolframkriesing** [comment]
@marcoemrich can you please create a subdomains for the session notes for us.
e.g. notes2018.jscraftcamp.org notes2019.jscraftcamp.org notes2020.jscraftcamp.org

**Comment by davelosert** [comment]
Just sumbled upon this as well (I am working on getting access, see #844).
The suggested approach won't work - we can't map Domains or Subdomains to URLs with a path in them. 

CName would only work if those pages already had another domain pointed to them. :/
But maybe we can configure this somehow within netlify? @lowsky do you know if this works with Netlify?

**Comment by Narigo** [comment]
@davelosert Can't we have a `CNAME` file in the GitHub repo and point the `notes20xx.` subdomains to the GitHub IP with an A record?

**Comment by davelosert** [comment]
Ah - i never knew this existed. Seems like it should work, true! :)
Sorry, didn't know this was a thing!

**Comment by Narigo** [comment]
Let's see what you can do once you have access 🙂 I guess it depends a bit on what the hosting service allows us to do with subdomains

**Comment by davelosert** [comment]
It works now for notes2019.jscraftcamp.org :)
We have to wait a bit to be able to enforce https, that's still open.

I created all Subdomains - but 2017 & 2018 are not hosted yet on github. Shall we activate this?
And for 2020, there is no repo yet.

**Comment by Narigo** [comment]
I may still have the notes repos for 2017 and 2018 on my private account if
I didn't transfer it yet...

David Losert <notifications@github.com> schrieb am Do., 13. Feb. 2020,
21:50:

**Comment by wolframkriesing** [comment]
works see https://notes2018.jscraftcamp.org
