### ISSUE TITLE
Contact sponsors via email

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#806]
We want all sponsor items to be covered and need to  contact sponsors therefore.
In the past years we wrote emails to previous sponsors.  Going through the past issues might reveal  a lot of them who are still interested ... or find new ways to find sponsors

see #570 for 2019 sponsors

**Comment by Narigo** [comment]
Don't forget to tell potential sponsors that they may post jobs at JSCC (see https://github.com/jscraftcamp/website/issues/788)
