### ISSUE TITLE
Find a location

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#807]
We need a location 
- for about 100 people, 
- with a lot of rooms and 
- space for break out sessions,
- an area where we can run the open space
- outside area would be really nice, it will be summer (Virtual Identity is a great example)

------

- Ask Virtual Identity
- maybe also CodeCentric
  - on 2 floors
  - more than 10 rooms available
  - open space room exists
  - will post some pics on slack
  - doing it on Friday is no problem

**Comment by wolframkriesing** [comment]
CodeCentric would have both suggested dates available see #808

**Comment by davelosert** [comment]
I talked with VI: It would be okay for them to host another JSCC. However, I did not clarify a date yet, but that shouldn't be a problem.

My suggestion:
Let's discuss which location we'd prefer in our call tomorrow and than move forward.

**Comment by wolframkriesing** [comment]
poll started in Slack channel

**Comment by wolframkriesing** [comment]
visited CodeCentric offices and decided to do it there. thanks
