### ISSUE TITLE
T-Shirt is not allowed to be null.

### ISSUE THREAD

**Issue by sebslomski** [jscraftcamp/website#81]
My participation PR build (https://github.com/jscraftcamp/website/pull/80) fails because of I'm not interested in a t-shirt (https://github.com/jscraftcamp/website/pull/80/files#diff-6ded8776bf456b08a0828e4612b48e50R11).
The documentation mentions: `We will have a limited number of t-shirts with the event and sponsor logos. If you want one: fit (W=women, M=Man) and size (S,M,L,XL), e.g. W-S or M-XL.` ... `If you want one`.
According to this docs I thought null was a legit option as well. Apparently it isn't.

I can't fix this by myself as I'm currently on vacation and on edge only. Also, I'm happy with empty string also :-)

**Comment by wolframkriesing** [comment]
Alternatively you can remove the entire line, that should work. Or just peep and I do it for you :)
