### ISSUE TITLE
Find a new (logo) color

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#810]
see how we did it in 2019 
https://twitter.com/JSCraftCamp/status/1106879993651572736

**Comment by michaelzoidl** [comment]
I would suggest using the same logo as the last year. For the color a poll like last year again? :) 

I've noticed that we never used yellow til now, so i would vote for this color 🎉

**Comment by wolframkriesing** [comment]
suggested colors collected,
now lets choose three, do a poll for 1 day and DONE

**Comment by wolframkriesing** [comment]
@michaelzoidl can we maybe pair on getting the new logo into the logo repo as a bonsai movie?
so we can start polling for the color with the new logo

**Comment by michaelzoidl** [comment]
Sounds good :)

**Comment by Narigo** [comment]
@michaelzoidl does a small mockup with the suggested colors, after that we can send it out on twitter

**Comment by wolframkriesing** [comment]
tweet and  poll is out https://twitter.com/JSCraftCamp/status/1232985098963890176

**Comment by wolframkriesing** [comment]
voting done, pink won
https://twitter.com/JSCraftCamp/status/1232985968346632192
