### ISSUE TITLE
Create 2020 page

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#811]
Re-do the page (for 2020)

**Comment by cowglow** [comment]
Is this replacing #717?

**Comment by cowglow** [comment]
Is this related to #797

**Comment by lowsky** [comment]
> Is this replacing #717?
> "Create marc_emmanuel..."

nope. I don't think so ;-)

**Comment by lowsky** [comment]
> Is this related to #797

Okay, good point. I think we have these 2 tasks:

- #797 new design: mainly migrate current one
	   should be done asap, as a base for #811
- #811 new page/info: 
	   adding with all the new infos, like location, sponsors, etc.

**Comment by wolframkriesing** [comment]
@lowsky @michaelzoidl  is the plan to build this page https://misty-paper-1043.animaapp.io/home in real?

**Comment by s1hofmann** [comment]
@michaelzoidl How could we best sync work packages? Would it be practicable if you build single components and whoever finds the time starts migrating single pages?
