### ISSUE TITLE
Ideas for kids

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#814]
Let's ask who would bring kids

**Comment by AgnesK** [comment]
To discuss:
 * kids track for older kids (>10); e.g. making your own website (simple html), TDD for kids, ...
 * kids room with toys; for which age? 0-3 // 4-10? 
 * rent (outdoor) toys: https://www.muenchen.de/rathaus/Stadtverwaltung/Referat-fuer-Bildung-und-Sport/Spielgeraeteverleih.html
 * hire a caretaker

**Comment by wolframkriesing** [comment]
in order to not publically expose all kids data, we will use an email where we collect the interest.
