### ISSUE TITLE
Sponsor needed for Beverages 🍼🍹🥛🍵🍻 - 💰💰💰💰💰

### ISSUE THREAD

**Issue by Narigo** [jscraftcamp/website#823]
## Why Drinks?

The human body is made out of 90% of water - a good reason to always stay hydratred. For a developer, it might only be 70% water and 20% coffee (which [we also search a sponsor for][coffee]). Still: we need some nice beverages for our guests to stay fluid. Help us by either sponsoring the drinks completely or let us help you with a selection we like!

## How does it work?

Cost are around 500,- Euro.
Ideally the sponsor orders drinks that get delivered to the location. Feel free to ping us here in this ticket about past experience of what and how much to order.
 
Last year we ordered the amount of drinks we thought will be enough. The cool thing is that most companies also take back the bottles that had not been opened yet. The bill will be sent to the sponsors address afterwards.

[coffee]: https://github.com/jscraftcamp/website/issues/825

**Comment by bananer** [comment]
My employer [AW Academy](https://awacademy.de) is interested in sponsoring the drinks. Our Brand Manager would like to organize this and get in contact with someone via email. Who should she write to?

**Comment by Narigo** [comment]
Hi @bananer - this is great news! Your brand manager can contact team@jscraftcamp.org to check the details. Thanks for the interest in sponsoring!

**Comment by Narigo** [comment]
JSCC2020 did not take place 😭
But there is hope! Check out JSCC22! You could sponsor this over here: https://github.com/jscraftcamp/website/issues/1078
