### ISSUE TITLE
Sponsor needed for renting chairs, beer benches, cuttlery 🍴🍴🍴💺 💺 💺 - 💰💰💰

### ISSUE THREAD

**Issue by Narigo** [jscraftcamp/website#830]
## Why chairs?
We have a big hall and not enough chairs available in the office. In order for all people to have a seat while gathering in the center of the open space we need to rent chairs.
We will also need some benches (Bierbaenke) for sitting outside.
Estimated cost ~300 Euro.

## How does it work?
Last year we contracted an external company, that was payed directly by the sponsor. We, the JSCraftCamp organizers, only organzied that the company delivers the right number of the chairs we wanted. Once they were delivered, the evening before the event volunteers set them up in the event space.

The payment will be done by the sponsor directly to the company where we rent the chairs from. We will put you in contact and you (the sponsor) can handle it from that point on.

**Comment by wolframkriesing** [comment]
not needed for this  year, codecentric has it all on site, yeah
