### ISSUE TITLE
Update page to state jscc20 (not jscc19 anymore)

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#831]
- update title
- add "jscc20 coming in summer"
- "date will be announced when known"
- archive the 2019 page (and link in footer)
- link 2020 sponsoring page to github sponsoring project

In #811 the page might be redone, this ticket is only meant to update the current site asap.

**Comment by lowsky** [comment]
Page is live 👍 , thanks, @patrickwire
