### ISSUE TITLE
Automate creating the core set of tickets for another JSCC

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#839]

**Comment by davelosert** [comment]
I started this in a new repository:
https://github.com/jscraftcamp/jscc-project-creator

Already implemented a little script that read all current issues and put it into a JSON-File.
Now I just have to write the correct mutation-queries to create those issues again and again. 
And maybe a nice little CLI in front ;)

**Comment by wolframkriesing** [comment]
sounds like a great idea, so we plan to have a session at #jscc20, right?
If not so, please re-open.
