### ISSUE TITLE
Create milestones

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#840]
We need:

- [x] have a suggestion
- [x] lets discuss it

- what milestones (e.g. order food 4 weeks before, start registration, close registration, ...)
- how do we do it? slack reminder, calendar appointment, github???
- visualize the milestones on the website, so people see when there are deadlines for shirt ordering, food ordering, etc.

**Comment by Narigo** [comment]
Based on https://github.com/jscraftcamp/website/wiki/Best-Practices-&-Reviews I'll create milestones based on their timing

**Comment by Narigo** [comment]
I've created a few more milestones. The issues still need to be added to these milestones. https://github.com/jscraftcamp/website/milestones?direction=asc&sort=due_date&state=open
