### ISSUE TITLE
Verify our URL

### ISSUE THREAD

**Issue by davelosert** [jscraftcamp/website#844]
I stumbled upon the setting to verify our URL (jscraftcamp.org) within Github yesterday (under Settings -> verified domains).

This will give us a nice little badge that our URL is actually owned by us. No must have - but a nice credibility addon in my eyes ;)

In order to verify, we will have to create a txt-record like this:
`_github-challenge-jscraftcamp.jscraftcamp.org. - TXT - 0091d96332`

@wolframkriesing : I remember you wanted to contact @marcoemrich about the account for our current domain. As soon as we have this, we can add the verification.
Or @marcoemrich can do it directly - would also work :)

**Comment by marcoemrich** [comment]
Hi David,

what exactly should I do? I think it is also possible to create additional
Admin Accounts, so you have access as well.

**Comment by davelosert** [comment]
Hi @marcoemrich,

would be great to have an admin account we can access, as we also want to create some subdomains this year. Then we didn't have to bother you all the time as you don't have too much time this year. :)

In the case of the ticket, you'd have to configure a subdomain `_github-challenge-jscraftcamp.jscraftcamp.org.` with a txt entry with the value `0091d96332`.

But if you can give a an admin account, I can do it myself :)

**Comment by marcoemrich** [comment]
Hallo David,

I added you as "Ansprechpartner Technik" for my Host Europe-Account. I'm
not sure, if this works. You should get an Email with your access. Please
take a look.

Thanks,
Marco

**Comment by davelosert** [comment]
@marcoemrich : I didn't get an E-Mail.
What I got was a verify code onto my cell phone at 1:18 AM last night from an unknown number - did you add my phone number there as well? 😄 

Which E-Mail adress of mine did you use?

**Comment by marcoemrich** [comment]
I used david.losert@virtual-identity.com, and yes I added you phone number
as well.

**Comment by davelosert** [comment]
Ah haha, there is the mistake. I am not working at VI anymore. :)
Please use thise one: david@david-losert.com :)

**Comment by marcoemrich** [comment]
Ok - I did. Does it work?

**Comment by davelosert** [comment]
I got the mail - however, I can not login as I have no password.
And trying to reset it does not work as I don't get a mail... :/

Maybe it got messed up because I never registered before changing my mail adress. You know - corner cases & software... it's hard ;) 

Maybe you can fully delete my account and re-insert it again?

Sorry for all this trouble :/

**Comment by marcoemrich** [comment]
Do you have a secure channel for exchanging a password, like Signal? I
would just give you my Admin Password. I dont think the "technische
Ansprechpartner"  will work :(

**Comment by davelosert** [comment]
I have signal, telegram, 1password... you can choose :)

**Comment by davelosert** [comment]
Aaand Done! :)
