### ISSUE TITLE
Fix registration page

### ISSUE THREAD

**Issue by davelosert** [jscraftcamp/website#845]
As soon as we'll merge #843 , the registration page will look a bit messed up:
![Bildschirmfoto 2020-02-07 um 10 04 54](https://user-images.githubusercontent.com/4287128/74016709-2ea7f200-4993-11ea-8fa3-6b59599d91e0.png)

We should fix this before opening the registration.

**Comment by lowsky** [comment]
After a quick look into it, I found that prism code highlighting does not out-of-the-box together with react.

Prism highlighting needs to be synced with react's rendering lifecycle.

Some details or background:
* https://betterstack.dev/blog/code-highlighting-in-react-using-prismjs/#heading-the-simplest-way-to-use-prismjs-in-react
* https://github.com/FormidableLabs/prism-react-renderer

Maybye, a better alternative will be to use any gatsby markdown plugin...

**Comment by lowsky** [comment]
-> https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/
