### ISSUE TITLE
Link old archive.org pages of our website

### ISSUE THREAD

**Issue by wolframkriesing** [jscraftcamp/website#846]
e.g. https://web.archive.org/web/20161101081713/http://jscraftcamp.org/
- [x] find the best links on archive.org for each year, to use later on the site
- [ ] use them on the site

**Comment by matthaias** [comment]
Just looked it up and found these links near to the event. Saw that there were links to the old events in the footer of the pages :)

* 2016: https://web.archive.org/web/20161011211857/http://jscraftcamp.org:80/
* 2017: https://web.archive.org/web/20170715150754/http://jscraftcamp.org:80/
* 2018: https://web.archive.org/web/20180809182443/http://jscraftcamp.org/
* 2019: https://web.archive.org/web/20190706093953/http://jscraftcamp.org/
