### ISSUE TITLE
Create Timeline from Milestones & Issues on Github

### ISSUE THREAD

**Issue by davelosert** [jscraftcamp/website#849]
**Context**: For the JSCC Organization, we are missing some sort of "Timeline" or visual time-board to see when certain things are due (e.g. Sponsors should be found 4 weeks before the event, chairs should be ordered on date dd.mm.) This would help us a lot in planning.

**Idea**: Create a board on our website that uses the Github API to pull Milestone-Data directly from Github and visualize it.

**Comment by Narigo** [comment]
The milestones should be available now and have dates set. For next year, we could at least put the "done x weeks before the event" in the Wiki, so we don't forget about it. Do you think the timeline would help in finding sponsors?

**Comment by Narigo** [comment]
I put up a wiki page here for reference: https://github.com/jscraftcamp/website/wiki/Timeline-to-organize

We should probably adjust or add things on the fly while we find out what is working well and what isn't 🙂
