### ISSUE TITLE
Register as a netlify open source team

### ISSUE THREAD

**Issue by lowsky** [jscraftcamp/website#852]
Currently I am using netlify to build and preview our PRs.

To move it to a jscraftcamp team, we should
register as a "open source team", which gives us a `Pro Plan` with the addition of free unlimited team members!

see  https://www.netlify.com/legal/open-source-policy/

To qualify for the Open Source plan, our project must adhere to the following criteria:
* [x] mention Netlify on our page.
* [x] Includes a license listed on the Open Source Initiative approved license list or a Creative Commons license that includes “attribution” or places the work in the public domain.
* [x] Features a Code of Conduct at the top level directory of the project repository or prominently in the documentation (with a link in the navigation, footer, or homepage).
* [x] Must feature a link to our service on your main page. You have two options:
      N. has premade badges for your convenience, or we may create your own link, which should read “This site is powered by Netlify”, and include a link back to their home page.
* [x] Must not be a commercial project, whether created by a company or an individual.

**Comment by wolframkriesing** [comment]
since all  items seem to be done,  i am  closing it, feel free to re-open if thats not the case
